### PR TITLE
Added Bambu Lab, removed deprecated and dead links

### PR DESCRIPTION
**Pull request by TheElbinho**
Added Bambu Lab as a manufacturer

Removed game assets, as they are either offline (Fabzat) or don't have an app anymore and make shady casino advertisements on their site (Toyze)

### CODE REVIEW

**Comment by TheElbinho** [comment]
Removed more dead links as per https://github.com/ad-si/awesome-3d-printing/issues/30#issue-2512444008 and https://github.com/ad-si/awesome-3d-printing/issues/29#issue-2293109020

**Comment by TheElbinho** [comment]
Also worked through the whole printer manufacturers section to clean up the links

**Review by asellingson28 — APPROVED** [review]
I agree with these changes

**Comment by ad-si** [comment]
Thanks!

**Pull request merged**
