### PR TITLE
add some more vendors, websites & products

### PR DESCRIPTION
**Pull request by supernovae**

### CODE REVIEW

**Comment by adius** [comment]
Thanks for the pull request!
Can you please format the changes as described in https://github.com/adius/awesome-3d-printing/blob/master/contributing.md,
then I can merge it!

**Comment by bdmorin** [comment]
I'm going to pick up this awesome-list, if you want to commit here: https://github.com/bdmorin/awesome-3d-printing.git

**Comment by ad-si** [comment]
@bdmorin I'd be happy about  a pull request with your changes 🙂

**Comment by bdmorin** [comment]
Oh, awesome, I thought the list had been abandoned!

**Pull request merged**
